before_install:
  - sudo aptitude -y -q install curl make libyaml-dev
  - git clone git://github.com/nddrylliog/rock.git 
  - cd rock
  - make rescue
  - cd ..
  - export PATH=$PATH:$PWD/rock/bin

script:
  - export OOC_LIBS=$PWD
  - rock -v samples/parse-events
  - samples/parse-events

